// Generated by the FlutterFire CLI. Web and Android carry real values for
// the `taskpoint-8aba0` project — the same one taskpoint_admin/ uses, so the
// app and the admin dashboard share one set of users and data.
//
// TaskPoint targets Android and web only — there is no ios/ folder in this
// project, so there are no iOS options here either. If iOS is ever added,
// run `flutterfire configure` and tick it; that regenerates this file.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    if (defaultTargetPlatform == TargetPlatform.android) return android;
    // Previously any non-Android platform silently fell back to the *web*
    // options. On a desktop or iOS build that produced a confusing
    // half-working Firebase rather than an honest failure, so an
    // unsupported platform now says so outright.
    throw UnsupportedError(
      'TaskPoint is configured for Android and web only — '
      '$defaultTargetPlatform is not supported. Run `flutterfire configure` '
      'to add it.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnHMemVouKj8lq4U-FfWnND5ZyA-VwJQ',
    appId: '1:871951039337:web:459cdaba9bfe3833575bf8',
    messagingSenderId: '871951039337',
    projectId: 'taskpoint-8aba0',
    authDomain: 'taskpoint-8aba0.firebaseapp.com',
    storageBucket: 'taskpoint-8aba0.firebasestorage.app',
    measurementId: 'G-3M2FC3GB05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUQcnUVjfx5GNO76BtV8UcNphV0AlINi0',
    appId: '1:871951039337:android:b7797438d085b7cc575bf8',
    messagingSenderId: '871951039337',
    projectId: 'taskpoint-8aba0',
    storageBucket: 'taskpoint-8aba0.firebasestorage.app',
  );
}
